top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/os
builddir     = /home/2019/y2019g28/httpd-2.4.41/os
VPATH        = /home/2019/y2019g28/httpd-2.4.41/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
