top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/modules/test
builddir     = /home/2019/y2019g28/httpd-2.4.41/modules/test
VPATH        = /home/2019/y2019g28/httpd-2.4.41/modules/test
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
