top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/modules
builddir     = /home/2019/y2019g28/httpd-2.4.41/modules
VPATH        = /home/2019/y2019g28/httpd-2.4.41/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

