top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/modules/http
builddir     = /home/2019/y2019g28/httpd-2.4.41/modules/http
VPATH        = /home/2019/y2019g28/httpd-2.4.41/modules/http

include $(top_srcdir)/build/special.mk

