top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/srclib
builddir     = /home/2019/y2019g28/httpd-2.4.41/srclib
VPATH        = /home/2019/y2019g28/httpd-2.4.41/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
