top_srcdir   = /home/2019/y2019g28/httpd-2.4.41
top_builddir = /home/2019/y2019g28/httpd-2.4.41
srcdir       = /home/2019/y2019g28/httpd-2.4.41/server/mpm
builddir     = /home/2019/y2019g28/httpd-2.4.41/server/mpm
VPATH        = /home/2019/y2019g28/httpd-2.4.41/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
